### ISSUE TITLE
`graph` Task not created.

### ISSUE THREAD

**Issue by Psyf** [graphprotocol/hardhat-graph#24]
I get `Error HH303: Unrecognized task graph` when trying to run `yarn hardhat graph` 

Here's what I have so far: 
- hardhat on `2.10.1-gzeon-c8fe47dd4` (which is 2.10.1 with the arbitrum nitro forking patch https://github.com/NomicFoundation/hardhat/issues/2995#issue-1318585332) 
- install hardhat-graph using `yarn add @graphprotocol/hardhat-graph`
- install dependencies using `yarn add @graphprotocol/graph-cli` and `yarn add @graphprotocol/graph-ts` (after which I seem to be able to do `yarn graph init`)

You can see the repo here: https://github.com/jezer0x/barren-wuffet/tree/graph

**Comment by dimitrovmaksim** [comment]
You have to import the plugin in your `[hardhat.config.ts](https://github.com/graphprotocol/hardhat-graph-demo/blob/main/hardhat.config.ts#L9)`

Also to use the extended hardhat config that comes with the plugin you will have to omit the type here https://github.com/jezer0x/barren-wuffet/blob/graph/hardhat.config.ts#L11 that is imported from hardhat here https://github.com/jezer0x/barren-wuffet/blob/graph/hardhat.config.ts#L1  

You can see the example config in the [hardhat-graph-demo repository](https://github.com/graphprotocol/hardhat-graph-demo/blob/main/hardhat.config.ts#L32-L47)

**Comment by Psyf** [comment]
That fixed it. Thanks!
