### ISSUE TITLE
Can`t update abi and data source via plugin on already created data source in local environment

### ISSUE THREAD

**Issue by mortum5** [graphprotocol/hardhat-graph#27]
I have local ganache instance and local graph instance and deploy via hardhat ethers. 

And problem that `update` subtasks try get abi from `https://api-localhost.etherscan` and i cant specify local abi. I also try use `add tasks` again with and without --merge-entities and it's failes with `Datasource or template with name Allocation already exists, please choose a different name`. 

Can you add support of local abi not just for first time add data source?

hardhat-graph: 0.1.0-alpha.2

**Comment by dimitrovmaksim** [comment]
The hardhat plugin is fetching the ABI from the `artifacts` folder which contains the compiled contracts by the `hardhat compile` task. This hardhat plugin's purpose is to develop your contracts and subgraphs simultaneously. It is not using etherscan to fetch the ABIs.

**Comment by mortum5** [comment]
But i use this code
```js
async function graph_update(contractName, contractAddress) {
    await hre.run('update', {
        contractName: contractName,
        address: contractAddress
    });
}
```

and see this error message

<img width="1712" alt="Снимок экрана 2023-02-07 в 14 22 52" src="https://user-images.githubusercontent.com/9256915/217231853-07c7067b-11d1-47e2-81c0-180ffc45d9c5.png">

**Comment by moconnell** [comment]
Looks like I'm getting the same error - I am calling `add` on top of an existing `subgraph` folder however:

```
- Add a new dataSource FooFooV1
  Initiating graph add command
- Add a new dataSource FooFooV1
- Fetching ABI from Etherscan
✖ Failed to fetch ABI from Etherscan: getaddrinfo ENOTFOUND api-hardhat.etherscan.io
✖ Failed to add a new dataSource DeVoxShamanSummonerV1: getaddrinfo ENOTFOUND api-hardhat.etherscan.io
Error HH604: Error running JSON-RPC server: ERROR processing /foo/evm/deploy/020_Graph_Init.ts:
Error: getaddrinfo ENOTFOUND api-hardhat.etherscan.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
For more info go to https://hardhat.org/HH604 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.
```

Shame it's not being actively developed btw. What's the alternative route, short of deploying stuff to Goerli or wherever and then using the regular Graph CLI?
