### ISSUE TITLE
Error while installing - "error Couldn't find match for "feat/smaller" "

### ISSUE THREAD

**Issue by luiscfaria** [graphprotocol/hardhat-graph#29]
I keep getting this error message when trying to install:

```
error Couldn't find match for "feat/smaller" in "refs/heads/1.3.x,refs/heads/1.4.x,refs/heads/master,refs/tags/v1.3.2,refs/tags/v1.4.10,refs/tags/v1.4.11,refs/tags/v1.4.7,refs/tags/v1.4.8,refs/tags/v1.4.9,refs/tags/v1.5.0,refs/tags/v1.5.1,refs/tags/v1.5.2,refs/tags/v1.6.0,refs/tags/v1.6.1,refs/tags/v1.6.2,refs/tags/v2.0.0" for "https://github.com/hugomrdias/concat-stream.git".
```

Installed from the repo: 

```
{
  ...
  "devDependencies": {
    "@graphprotocol/graph-cli": "^0.45.1",
    "@graphprotocol/hardhat-graph": "https://github.com/graphprotocol/hardhat-graph"
    ...
  }
}
```

Is there any solution for this?

**Comment by dimitrovmaksim** [comment]
Hi, this seems to be an issue with the latest version of the graph-cli https://github.com/graphprotocol/graph-tooling/issues/1264

**Comment by luiscfaria** [comment]
When I install with yarn add -D @graphprotocol/hardhat-graph I am able to install the package with no problem but I get another error when I try to run the hardhat node with "npx hardhat node --hostname 0.0.0.0"
I get
```
 Error: Cannot find module '@graphprotocol/graph-cli/src/command-helpers/spinner'
```
Which is used in node_modules/@graphprotocol/hardhat-graph/dist/helpers/generator.js

**Comment by dimitrovmaksim** [comment]
It already should be trying to import it from `dist` https://github.com/graphprotocol/hardhat-graph/blob/main/src/helpers/generator.ts#L3

Try adding the commit hash when installing from github `"@graphprotocol/hardhat-graph": "https://github.com/graphprotocol/hardhat-graph#e752ff8722f846564ef5e5f2cfeb14be82de0549" to get the latest version

**Comment by dimitrovmaksim** [comment]
> When I install with yarn add -D @graphprotocol/hardhat-graph I am able to install the package with no problem

The version installed from [`npmjs`](https://www.npmjs.com/package/@graphprotocol/hardhat-graph) is old an incompatible with the newest graph-cli versions. I don't have the required access to release a newer version
